include: package:very_good_analysis/analysis_options.3.0.1.yaml
analyzer:
  exclude:
    - build/**
    - lib/**.g.dart

linter:
  rules:
    avoid_print: false
    file_names: false
    no_default_cases: false
    public_member_api_docs: false
